### ISSUE TITLE
Bold item in a list

### ISSUE THREAD

**Issue by ccbc** [adhocore/htmlup#17]
## Introduction

Even if the code is 6 years old and a newer version exists,  I'm trying to integrate it to a small wiki script. Anybody noticed that we cannot use bold on the first letter/word on an item of a list?

- [X] Bug/Issue
- [ ] Feature request
- [ ] General stuff

## Describe the bug/issue

I wanted to do this:

- **This text is in bold**

### What happened

However, it will display

- This text is in bold**

Without converting it in bold, but removing the first 2 stars.

### What is expected

I need your help to find a quick fix. I looked and tried some tweaks, but without success.

### Sample code

`            // list
            if ($ul = in_array($mark12, array('- ', '* ', '+ ')) OR preg_match('/^\d+\. /', $mark12)) {
                $wrapper = $ul ? 'ul' : 'ol';
                if (empty($inList)) {
                    $stackList[] = "</$wrapper>";
                    $markup .= "\n<$wrapper>\n";
                    $inList = true;
                    $nestLevel++;                    
                }
                $markup .= "\t<li>".ltrim($trimmedLine, '-*0123456789. ');
                if ( $ul = in_array($nextMark12, array('- ', '* ', '+ '))
                    OR preg_match('/^\d+\. /', $nextMark12)
                ) {
                    $wrapper = $ul ? 'ul' : 'ol';
                    if ($nextIndent > $indent) {
                        $stackList[] = "</li>\n";
                        $stackList[] = "</$wrapper>";
                        $markup .= "\n<$wrapper>\n";
                        $nestLevel++;                        
                    } else {
                        $markup .= "</li>\n";
                    }
                    if ($nextIndent < $indent) {
                        $shift = intval( ($indent - $nextIndent)/4 );
                        while ($shift--) {
                            $markup .= array_pop($stackList);
                            if ($nestLevel > 2) {
                                $markup .= array_pop($stackList);                            
                            }
                        }
                    }
                } else {
                    $markup .= "</li>\n";
                }
                continue;
            }
            if (isset($inList)) {
                $markup .= $trimmedLine;
                continue;
            }
`

### Environment

- OS: N/A
- PHP version: 7.4.1
- htmlup version: Jun 12, 2014

**Comment by ccbc** [comment]
Found the fix. See below.

```
            // list
            if ($ul = in_array($mark12, array('- ', '* ')) OR preg_match('/^[0-9.]+\s/', $mark12)) {
                $wrapper = $ul ? 'ul' : 'ol';
                if (empty($inList)) {
                    $stackList[] = "</$wrapper>";
                    $markup .= "\n<$wrapper>\n";
                    $inList = true;
                    $nestLevel++;                    
                }
                $markup .= "\t<li>".substr($trimmedLine, 2);
                if ( $ul = in_array($nextMark12, array('- ', '* ')) OR preg_match('/^[0-9.]+\s/', $nextMark12)) {
                    $wrapper = $ul ? 'ul' : 'ol';
                    if ($nextIndent > $indent) {
                        $stackList[] = "</li>\n";
                        $stackList[] = "</$wrapper>";
                        $markup .= "\n<$wrapper>\n";
                        $nestLevel++;                        
                    } else {
                        $markup .= "</li>\n";
                    }
                    if ($nextIndent < $indent) {
                        $shift = intval( ($indent - $nextIndent)/4 );
                        while ($shift--) {
                            $markup .= array_pop($stackList);
                            if ($nestLevel > 2) {
                                $markup .= array_pop($stackList);                            
                            }
                        }
                    }
                } else {
                    $markup .= "</li>\n";
                }
                continue;
            }
            if (isset($inList)) {
                $markup .= $trimmedLine;
                continue;
            }
```

**Comment by adhocore** [comment]
oh thanks but why again closed? 😁
